openapi: 3.0.1
info:
  title: Inditex API prices
  description: Inditex API for e-commerce on the prices table and associated products
  version: 1.0.0

paths:
  /price:
    get:
      parameters:
        - $ref: './requests/getPricesRequest.yml#/productId'
        - $ref: './requests/getPricesRequest.yml#/brandId'
        - $ref: './requests/getPricesRequest.yml#/applicationDate'
      tags:
        - GetPrices
      responses:
        '200':
           description: Search response in the prices table
           content: 
             application/json:
               schema:
                $ref: './responses/getPricesResponse.yml'
        '400':
          description: List of errors
          content: 
            application/json:
              schema:
                $ref: './responses/errorResponse.yml'
        '500':
          description: List of errors
          content: 
              application/json:
                schema:
                  $ref: './responses/errorResponse.yml'

      operationId: Get Final Price
      summary: Get data form prices table
      description: Retrieves the product ID, brand ID, rate ID, and final price from the prices table based on the provided product ID, brand ID, and application date.