openapi: 3.0.1
info:
  title: Inditex API prices
  description: Inditex API for e-commerce on the prieces table and associated products
  version: 1.0.0

paths:
  /price:
    get:
      parameters:
         - $ref './requests/productId.yml'
         - $ref './requests/brandId.yml'
         - $ref './requests/aplicationDate.yml'
      responses:
         '200':
             description: Search response in the prices table
             content: 
                 application/json:
                     schema:
                         $ref './responses/getPricesResponse.yml'
         '400':
             description: List of errors
             content: 
                 application/json:
                     schema:
                         $ref './responses/errorResponse.yml'
         '500':
             description: List of errors
             content: 
                 application/json:
                     schema:
                         $ref './responses/errorResponse.yml'

      operationId: Obtener precio final
      summary: Obtencion de los datos de la tabla price
      description: Obtencion de los datos identificador producto, identificador cadena, tarifa a aplicar, 
                   fechas de aplicacion y precio final a aplicar
  