CREATE TABLE prices (
	rate_id BIGINT AUTO_INCREMENT PRIMARI KEY,
	brand_id INTEGER FOREIGN KEY NOT NULL,
	start_date TIMESTAMP NOT NULL,
	end_date TIMESTAMP NOT NULL,
	product_id INTEGER NOT NULL,
	priority INTEGER NOT NULL,
	price DECIMAL(10,2),
	curr CHAR(3)
);